#删掉文件名的-push
server:
  port: 8080
spring:
  application:
    name: blog
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #name: defaultDataSource
    url: jdbc:mysql://你的ip:3306/blog?serverTimezone=UTC
    username: 账号
    password: 密码
    hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: ip
    port: 6379
    password: 密码
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true # 开启驼峰命名法

aliyun:
  url: "http://xxxx.top"
  endpoint: "oss-cn-hangzhou.aliyuncs.com"
  accessKeyId: "xxxx"
  accessKeySecret: "xxxx"
  bucketName: "my-blog-pictures"